try {
  let person = "Foluso";
  console.log(person);
} catch (error) {
  console.log(error);
}
